// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66jTrpfauH9b9imuiJAfrRPBZTHzFpAo',
    appId: '1:307209002963:web:742df61e9388b9993b1926',
    messagingSenderId: '307209002963',
    projectId: 'test-app-38038',
    authDomain: 'test-app-38038.firebaseapp.com',
    storageBucket: 'test-app-38038.appspot.com',
    measurementId: 'G-8LEF0NZTJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQD0bmRtzkGcl8kud_NQcpZGHx6vxNjZA',
    appId: '1:307209002963:android:b9367914deb392f43b1926',
    messagingSenderId: '307209002963',
    projectId: 'test-app-38038',
    storageBucket: 'test-app-38038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6YnEmgbYh1rkFAhFd1IeRkL4vJEZGWI',
    appId: '1:307209002963:ios:0a072dc7952a20e13b1926',
    messagingSenderId: '307209002963',
    projectId: 'test-app-38038',
    storageBucket: 'test-app-38038.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-6YnEmgbYh1rkFAhFd1IeRkL4vJEZGWI',
    appId: '1:307209002963:ios:6c11f56d3d0a4cd63b1926',
    messagingSenderId: '307209002963',
    projectId: 'test-app-38038',
    storageBucket: 'test-app-38038.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
